[build]
  command = "npm install && npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

[build.environment]
  NODE_ENV = "production"

# Redirect all traffic to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https:;"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
    
# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for service worker
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"
